# Generated by Django 3.1.4 on 2020-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201214_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3),
            preserve_default=False,
        ),
    ]
