# Generated by Django 3.1.4 on 2020-12-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201225_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
    ]
