# Generated by Django 3.1.4 on 2020-12-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coord',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
