# Generated by Django 3.1.4 on 2020-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201226_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='atmosphere_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='hospitality_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
