# Generated by Django 3.1.4 on 2020-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201226_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='atmosphere_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='hospitality_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=-33.865143, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=151.2099, max_digits=11),
        ),
    ]
