# Generated by Django 3.1.4 on 2020-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201226_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=-33.865143, max_digits=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=151.2099, max_digits=12),
        ),
    ]
