# Generated by Django 3.1.4 on 2020-12-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20201226_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restaurant_name',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
